permissions:
  contents: read
name: Run Prisma Migrations

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment name'
        required: false
        default: 'production'

jobs:
  migrate:
    name: Prisma migrate deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DIRECT_URL: ${{ secrets.DIRECT_URL }}
      NODE_ENV: production
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Create .env for Prisma
        run: |
          printf "DATABASE_URL=%s\n" "${{ secrets.DATABASE_URL }}" > .env
          printf "DIRECT_URL=%s\n" "${{ secrets.DIRECT_URL }}" >> .env

      - name: Assert DATABASE_URL and DIRECT_URL exist
        run: |
          if [ -z "$DATABASE_URL" ]; then
            echo "::error::DATABASE_URL is empty"; exit 1; fi
          if [ -z "$DIRECT_URL" ]; then
            echo "::error::DIRECT_URL is empty"; exit 1; fi
          echo "Env vars present."

      - name: Prisma Version
        run: npx prisma -v

      - name: Prisma Generate
        run: npm run prisma:generate

      - name: Run migrations (deploy)
        run: npm run prisma:deploy
